#pragma config(Motor,  port1,           MotorRB,       tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port3,           MotorLF,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           MotorLB,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          MotorRF,       tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
				motor(port1) = vexRT(Ch2);
				motor(port10) = vexRT(Ch2);
        motor(port3) = vexRT(Ch3);
        motor(port4) = vexRT(Ch3);
 //Functioning correctly with above set motor configuration as of 12/7/2018 09:25AM
        //Programed by Andrew Henke

        }
}
